In [1]:
# !pip install pandas

In [5]:
import numpy as np
import pandas as pd

### 1. 비만도 측정

In [3]:
w = input()
t = input()
weight = float(w)
tall = float(t)
result = weight/(tall*tall)
if result < 18.5:
    print('저체중')
elif 18.5 <= result < 25.0:
    print('정상')
elif 25.0 <= result < 30.0:
    print('과체중')
elif 30.0 <= result:
    print('비만')

19
180
저체중


### 2. 10의 자리수

In [4]:
n = int(input())
result = n%10
print(result)

1
1


### 3. 약수만 뽑아

In [5]:
n = int(input())
result = []
for i in range(1, n+1):
    if n%i == 0:
        result.append(i)
for i in result:
    print(i)

12
1
2
3
4
6
12


### Numpy
+ np.array
+ .reshape
+ list, array

### 4. 재배열

In [6]:
import numpy as np

s = input().split(',')
# print(s)
array=[]
for i in s:
    array.append(int(i))
# print(array)
result = np.array(array).reshape(4,5)
print(result)

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Pandas
+ .loc
+ .iloc

### 5. 특정 행 뽑기

In [8]:
import pandas as pd

df = pd.read_csv("country.csv", index_col=0)

print(df.loc['china'])
print(df.iloc[1:4, :])

gdp               1.409250e+09
population        1.415000e+05
gdp_per_capita    9.959364e+03
Name: china, dtype: float64
              gdp  population  gdp_per_capita
japan   516700000       12718    40627.457147
korea   169320000        5180    32687.258687
usa    2041280000       32676    62470.314604


### Pandas
+ df[df["구분"]=="Child"]
+ .groupby(['성별'])['나이'].mean()
+ .transform(mean)
+ .transpose(), .T
+ df if문

### 6. 특정 행 평균

In [9]:
import pandas as pd

df = pd.read_csv("table.csv")

sort = df[df["구분"]=="Child"]
result = sort.groupby(['성별'])['나이'].mean()
result = pd.DataFrame(result)
result = result.transpose()
print(result)
# result = df.groupby('성별')['나이'].agg(**{'나이':'mean'})
# result = result.transpose()
# print(result)

성별    Female      Male
나이  9.207547  8.047619


### Pandas
+ ordering = df[['Name', 'Attend']]
+ df.rename(columns={'Name':'Attend', 'Attend':'Name'})
+ .sort_index(ascending=False)
+ set_index, axis, inplace
+ header

### 7. 특정 행 묶어서 정렬

In [60]:
import pandas as pd

df = pd.read_csv("drink.csv")
# print(df)
order = df[['Name', 'Attend']]
# print(order)
rename = df.rename(columns={'Name':'Attend', 'Attend':'Name'})
# print(rename)
cal = rename.groupby('Attend')['Name'].sum()
# sort = sort.rename(columns={'Name', 'Attend'})
# print(cal)
sort = cal.sort_index(ascending=False)
# print(sort)
s = sort.sum()
result = sort/s
# result.drop(result.index[0])
# print(result)
# res = df.groupby('Name')['Attend'].agg(**{'Count':'sum'})
# s = res.sum()
# result = res/s
# print(result)

Attend
D    0.166667
C    0.166667
B    0.250000
A    0.333333
Name: Name, dtype: float64

### Pandas
+ del, .drop, .pop
+ merge, join, concat
+ head(), tail(), info(), dtype, describe()

### 8. 특정 칼럼 계산

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv("drink2.csv")

value = df.loc[:,'caffeine_content']
mean = value.mean()
res = []
for i in value:
    res.append((i-mean)*(i-mean))
result = sum(res)
result = result/(len(value)-1)
result = np.sqrt(result)
print(result)

36.93623849670827


### Pandas
+ assign()
+ lamda
+ map
+ apply()
+ filter()